services:
  - name: clickhouse-logs
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    port: 8123
    healthCheckPath: /ping
    envVars:
      - key: CLICKHOUSE_USER
        value: default
      - key: CLICKHOUSE_PASSWORD
        generateValue: true
    disk:
      name: clickhouse-data
      mountPath: /var/lib/clickhouse
      sizeGB: 10