services:
  - name: clickhouse-logs
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: CLICKHOUSE_USER
        value: default
      - key: CLICKHOUSE_PASSWORD
        value: "123456"
      - key: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
        value: "1"
    disk:
      name: clickhouse-data
      mountPath: /var/lib/clickhouse
      sizeGB: 10